#eureka配置
eureka: 
 client: 
  serviceUrl: 
    defaultZone: http://47.93.229.100:8761/eureka/
 instance: 
  prefer-ip-address: true
  lease-expiration-duration-in-seconds: 30
  lease-renewal-interval-in-seconds: 10