swagger:  
   enable: true  # 是否开启swagger，建议生产关闭，默认true
   basePackage: com.bqr.framework.sample.web  #swagger扫描的api包，不能为空
   title: 接入API列表  # 标题
   description: 接入API列表 #描述
   groupName: 测试组

spring:
  datasource:
    url: jdbc:mysql://rm-uf69j55wv3m56puj5o.mysql.rds.aliyuncs.com:3306/b2b_market
    username: root
    password: XiangYR-816
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: 47.93.229.100
    port: 5672
    username: rabbitmq_bqr
    password: rabbitmq_bqr

    
mybatis:
    type-aliases-package: com.bqr.framework.sample.entity


#redis:
#  cluster-nodes: 10.10.3.71:7001
#  expire-seconds: 1200000
#  command-timeout: 5000


#xxljob:
#  port: 9993
#  appname: bqr-framrework-xxljob
#  addresses: http://127.0.0.1:8080/xxl-job-admin
##  addresses: http://47.93.229.100:8080/xxl-job-admin
#  logpath: xxljobLogs









